spring:
  profiles:
    active: dev

  jackson:
    serialization:
      fail-on-empty-beans: false
  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  application:
    name: baronboost

stripe:
  secretKey: ${STRIPE_SECRET_KEY}