spring:
  config:
    import: optional:file:.env[.properties]

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  sql:
    init:
      mode: always

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG