spring:
  config:
    import: optional:file:.env[.properties]
  
  
  datasource:
    url: jdbc:postgresql://localhost:6001/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true


  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

stripe:
  secretKey: ${STRIPE_SECRET_KEY_TEST}